name: better-cloudflare-ip
on:
  schedule:
    - cron: '45 7 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-better-cloudflare-ip
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync better-cloudflare-ip
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/badafans/better-cloudflare-ip.git"
          source_branch: "master"
          destination_branch: "better-cloudflare-ip"
          github_token: ${{ secrets.PAT }}
