name: CorePress Theme
on:
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-CorePress Theme
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync CorePress Theme
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ghboke/CorePressWPTheme.git"
          source_branch: "main"
          destination_branch: "CorePress Theme"
          github_token: ${{ secrets.PAT }}
