name: freenom-py
on:
  schedule:
    - cron: '27 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-freenom-py
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync freenom-py
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Oreomeow/freenom-py.git"
          source_branch: "main"
          destination_branch: "freenom-py"
          github_token: ${{ secrets.PAT }}
