name: iptv-live
on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-iptv-live
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync iptv-live
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/YueChan/Live.git"
          source_branch: "main"
          destination_branch: "iptv-live"
          github_token: ${{ secrets.PAT }}
		  
