name: Tvlist-awesome-m3u-m3u8
on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Tvlist-awesome-m3u-m3u8
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Tvlist-awesome-m3u-m3u8
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/imDazui/Tvlist-awesome-m3u-m3u8.git"
          source_branch: "master"
          destination_branch: "Tvlist-awesome-m3u-m3u8"
          github_token: ${{ secrets.PAT }}
