name: x-ui
on:
  schedule:
    - cron: '1 8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-x-ui
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync x-ui
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/vaxilu/x-ui.git"
          source_branch: "main"
          destination_branch: "x-ui"
          github_token: ${{ secrets.PAT }}
